# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
sudo: required

services:
  - docker

branches:
  only:
    - master

install: true

language: minimal

jobs:
  include:
    - stage: compile-and-test
      script: ./travis/compile-and-test-docker.sh
    - stage: deploy-album-recommendation
      if: branch = master AND type IN (push,cron)
      script: ./travis/deploy-album-recommendation-searcher-docker.sh

